version: "3.9"
services:
    rpy_jupyter:
      image: jupyter/datascience-notebook:latest
      environment:
          - NOTEBOOK_ARGS=--port=8123 --NotebookApp.password='' --NotebookApp.token=''
      ports:
              - "8123:8123"
      volumes:
          - ./data:/home/jovyan/data
          - ./notebooks:/home/jovyan/work
