version: "3.9"
services:
    rpy_jupyter:
      build:
        dockerfile: Dockerfile
        context: ./
      environment:
          - NOTEBOOK_ARGS=--port=${PORT} --NotebookApp.password='' --NotebookApp.token=''
      ports:
          - "${PORT}:${PORT}"
      volumes:
          - ./data:/home/jovyan/data
          - itnotebooks:/home/jovyan/work
          # - ./work:/home/jovyan/work

volumes:
  itnotebooks:
    driver_opts:
      type: "cifs"
      o: "addr=fcm.net,username=ituser,password=ioas09mq,mfsymlinks,uid=1000,suid,rw"
      device: "//fcm.net/it/itnotebook"
